#!groovy

// Generated by IBM TransformationAdvisor
// Tue Oct 22 11:23:13 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}